name: Bug Report
description: Something is not working correctly in-game
labels: ["bug"]
body:
  - type: input
    id: mod-version
    attributes:
      label: Mod Version
      description: Which version of the mod are you running?
      placeholder: "e.g. 0.12.0"
    validations:
      required: true
  - type: input
    id: pz-version
    attributes:
      label: PZ Build Version
      description: Which Project Zomboid build are you on?
      placeholder: "e.g. 42.13.0"
    validations:
      required: true
  - type: dropdown
    id: multiplayer
    attributes:
      label: Singleplayer or Multiplayer?
      options:
        - Singleplayer
        - Multiplayer (host)
        - Multiplayer (client)
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe what went wrong. Include the recipe name or item if relevant.
      placeholder: "When I try to craft [recipe name], the game..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What should have happened?
      description: What did you expect to happen instead?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we trigger this bug?
      placeholder: |
        1. Open crafting menu
        2. Select [recipe]
        3. Click craft
        4. See error
  - type: textarea
    id: console-log
    attributes:
      label: Console log errors
      description: |
        Paste any relevant errors from console.txt
        (found in C:\Users\[you]\Zomboid\ on Windows).
      render: shell
  - type: textarea
    id: mod-list
    attributes:
      label: Other mods installed
      description: List other mods that might be relevant (especially zReVaccin, EHR, ZScienceSkill).
  - type: textarea
    id: sandbox-settings
    attributes:
      label: Relevant sandbox settings
      description: |
        If the bug involves sandbox options (yield multiplier, purity system,
        health hazards, etc.), note which are enabled and their values.
